print("Simple Calculator")
print("-----------------")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")
print("5. Exit")

choice = int(input("Enter your choice (1-5):"))
print("You selected:", choice)
